/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IP2Decimal.java
 *
 * Created on Mar 28, 2010, 7:11:30 PM
 */

package pckg;

import javax.swing.JOptionPane;

/**
 *
 * @author stevan
 */
public class IP2Decimal extends javax.swing.JFrame {

    /** Creates new form IP2Decimal */
    public IP2Decimal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tIP1 = new javax.swing.JTextField();
        tIP2 = new javax.swing.JTextField();
        tIP3 = new javax.swing.JTextField();
        tIP4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tDecAdresa = new javax.swing.JTextField();
        dAutor = new javax.swing.JButton();
        dKonvertuj = new javax.swing.JButton();
        dKraj = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tURL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("URL Faker");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("Malicious IP address:");

        tIP1.setColumns(3);

        tIP2.setColumns(3);

        tIP3.setColumns(3);

        tIP4.setColumns(3);

        jLabel2.setText("Faked address:");

        tDecAdresa.setEditable(false);

        dAutor.setText("About");
        dAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dAutorActionPerformed(evt);
            }
        });

        dKonvertuj.setText("Convert");
        dKonvertuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dKonvertujActionPerformed(evt);
            }
        });

        dKraj.setText("Exit");
        dKraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dKrajActionPerformed(evt);
            }
        });

        jLabel3.setText("Malicious URL address:");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 10));
        jLabel4.setText("(format: www.xxx.com)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tDecAdresa, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(tIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tIP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tURL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dKonvertuj)
                                    .addComponent(dAutor))
                                .addComponent(dKraj)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tIP1, tIP2, tIP3, tIP4});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dAutor, dKonvertuj, dKraj});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dKonvertuj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dKraj))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tIP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tIP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tIP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tDecAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tIP1, tIP2, tIP3, tIP4});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dAutorActionPerformed
        JOptionPane.showMessageDialog(this, "Stevan Cvetkovic\ncvetkovic.stevan@gmail.com\nMarch 2010.", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_dAutorActionPerformed

    private void dKonvertujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dKonvertujActionPerformed
        if(!this.tURL.getText().equals(""))
        {
            Functions f = new Functions();

            String s = f.getIPAddress(this.tURL.getText());

            // konverzija u char
            char[] nS = s.toCharArray();
            for(int i=0; i<s.length(); i++)
                nS[i] = s.charAt(i);

            // indexes
            int ind1 = 0;
            int ind2 = 0;
            int ind3 = 0;

            // finds dot's indexes
            for(int i=0; i<nS.length; i++)
                if(nS[i] == '.')
                {
                    ind1 = i;
                    break;
                }

            for(int i=ind1+1; i<nS.length; i++)
                if(nS[i] == '.')
                {
                    ind2 = i;
                    break;
                }

            for(int i=ind2+1; i<nS.length; i++)
                if(nS[i] == '.')
                {
                    ind3 = i;
                    break;
                }

            // extraction of each part of IP address
            // depending on the position of the dots
            String[] nIP1 = new String[ind1];
            String[] nIP2 = new String[ind2-ind1-1];
            String[] nIP3 = new String[ind3-ind2-1];
            String[] nIP4 = new String[nS.length-ind3-1];

            int j=0;
            for(int i=0; i<ind1; i++)
                nIP1[i] = String.valueOf(nS[i]);

            for(int i=ind1+1; i<ind2; i++)
            {
                nIP2[j] = String.valueOf(nS[i]);
                j++;
            }

            int k=0;
            for(int i=ind2+1; i<ind3; i++)
            {
                nIP3[k] = String.valueOf(nS[i]);
                k++;
            }

            int l=0;
            for(int i=ind3+1; i<nS.length; i++)
            {
                nIP4[l] = String.valueOf(nS[i]);
                l++;
            }

            this.tIP1.setText(Functions.array2String(nIP1));
            this.tIP2.setText(Functions.array2String(nIP2));
            this.tIP3.setText(Functions.array2String(nIP3));
            this.tIP4.setText(Functions.array2String(nIP4));

            String rez = f.Ip2Decimal(this.tIP1.getText(), this.tIP2.getText(), this.tIP3.getText(), this.tIP4.getText());

            this.tDecAdresa.setText(rez);
        }
        else if(this.tIP1.getText().isEmpty() || this.tIP2.getText().isEmpty() || this.tIP3.getText().isEmpty() || this.tIP4.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "First you need to enter IP or URL address!", "Error", JOptionPane.ERROR_MESSAGE);
        else
        {
            Functions f = new Functions();

            String rez = f.Ip2Decimal(this.tIP1.getText(), this.tIP2.getText(), this.tIP3.getText(), this.tIP4.getText());

            this.tDecAdresa.setText(rez);
        }
    }//GEN-LAST:event_dKonvertujActionPerformed

    private void dKrajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dKrajActionPerformed
        System.exit(0);
    }//GEN-LAST:event_dKrajActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IP2Decimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dAutor;
    private javax.swing.JButton dKonvertuj;
    private javax.swing.JButton dKraj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tDecAdresa;
    private javax.swing.JTextField tIP1;
    private javax.swing.JTextField tIP2;
    private javax.swing.JTextField tIP3;
    private javax.swing.JTextField tIP4;
    private javax.swing.JTextField tURL;
    // End of variables declaration//GEN-END:variables

}